### ISSUE TITLE
SSL error connecting to foreign hub from `koji-steal-build`

### ISSUE THREAD

**Issue by ben-alkov** [projectatomic/osbs-box#85]
Command:
```bash
docker \
exec -it \
osbsbox_koji-hub_1 \
koji-steal-build osbs-buildroot-container \
--kojihub https://kojihub \
--kojiroot http://kojiroot
```

```pythyon
Traceback (most recent call last):
  File "/usr/local/bin/koji-steal-build", line 104, in <module>
    BuildStealer(args.nvr, args.kojihub, args.kojiroot).start()
  File "/usr/local/bin/koji-steal-build", line 28, in start
    self.get_build_info()
  File "/usr/local/bin/koji-steal-build", line 34, in get_build_info
    self.build_info = self.session.getBuild(self.nvr, strict=True)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2016, in __call__
    return self.__func(self.__name, args, opts)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2475, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2397, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2436, in _sendOneCall
    r = self.rsession.post(handler, **callopts)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```

**Comment by lcarva** [comment]
Probably need to install the internal root CA in the `osbsbox_koji-hub_1` container.

**Comment by ben-alkov** [comment]
Exactly :smile:

**Comment by ben-alkov** [comment]
Probably something like (on Fedora/RH):
1. `cd /etc/pki/ca-trust/source/anchors`
1. `curl https://password.com/foo.crt > foo.crt`
1. `update-ca-trust extract`
